### ISSUE TITLE
create_covariance.py fails for binned/rebinned systematics

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1043]
Afternoon - 

I get this error:
```Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1564, in <module>
    raise e
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1560, in <module>
    create_covariance(config, args)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1441, in create_covariance
    extracovdict)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 756, in get_contributions
    cov, summary = get_cov_from_covfile(df, os.path.expandvars(value), muopt_scales[key])
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 699, in get_cov_from_covfile
    if len(np.argwhere(data['CIDstr'].array == row['CID1'])) == 0:
  File "/home/bap37/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/bap37/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CIDstr'```

when running create_covariance.py on binned/rebinned data. Unbinned is ok. 

of note seems to be this line:

  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 699, in get_cov_from_covfile
    if len(np.argwhere(data['CIDstr'].array == row['CID1'])) == 0:

output logs are here:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-V5/7_CREATE_COV/ALL_DATA_BINNED_DATA_FULL

**Comment by RickKessler** [comment]
The input has some VPEC requests but there is no VPEC systematic. In RICK.input I deleted four lines with VPEC info, and create_cov runs.
