### ISSUE TITLE
create_cov crash

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1095]
crash logs in `/scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_V_LAMBDACDM/7_CREATE_COV/FR_COV_OMW_NO_OMPRI_0/output/SCRIPTS_COVMAT`

```
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1722, in <module>
    create_covariance(config, args)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1584, in create_covariance
    data = get_hubble_diagrams(data_dir, args, config)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 499, in get_hubble_diagrams
    header_info = read_header_info(hd_file)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 369, in read_header_info
    arg = wd_list[2].split(',')
IndexError: list index out of range
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1726, in <module>
    raise e
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1722, in <module>
    create_covariance(config, args)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1584, in create_covariance
    data = get_hubble_diagrams(data_dir, args, config)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 499, in get_hubble_diagrams
    header_info = read_header_info(hd_file)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 369, in read_header_info
    arg = wd_list[2].split(',')
IndexError: list index out of range
```

**Comment by RickKessler** [comment]
VERSION_PHOTOMETRY(DATA) has blank argument, likely from mixing outputs from older and newer SNANA versions. Fix is to substitute UNKNOWN for blank arg.
