### ISSUE TITLE
BBC submit_batch index out of range error

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1239]
Error:
```
1  Write FAIL to done stamp file:
  2      ALL.DONE
  3 [IndexError('list index out of range'), 'Crashed while preparing batch jobs.', 'Che    ck Traceback']
  4 Traceback (most recent call last):
  5   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs    .py", line 398, in <module>
  6     program.submit_prepare_driver()
  7   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_bbc.p    y", line 189, in submit_prepare_driver
  8     self.bbc_prep_version_match()
  9   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_bbc.p    y", line 514, in bbc_prep_version_match
 10     self.bbc_prep_1version_match()
 11   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_bbc.p    y", line 665, in bbc_prep_1version_match
 12     version = version_list2d[idir][iver]
```

Directory: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/6_BIASCOR/P21NOM_SIM

**Comment by RickKessler** [comment]
For LOWZ and FOUNDATION there are 25 sim-data samples, but there is only one DES sample ... so BBC is not able to match data sets. It needs 25 DES samples.

**Comment by OmegaLambda1998** [comment]
That was it
