### ISSUE TITLE
KeyError: 'NEVT_LC_CUTS' 

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#1275]
In all the *SIMDATA folders 
`$PIPPIN_OUTPUT/LSST_COMBINED_CC_V3/2_LCFIT/FIT_*SIMDATA/`

this is the error : 

```
# merge_driver:          Remove BUSY_MERGE_CPU0008.LOCK for T_midnight=83701
['Check CPU0008*.LOG for merge crash']
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/submit_batch/submit_batch_jobs.py", line 416, in run_
merge_driver
    program.merge_driver()
  File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_prog_base.py", line 1449, in merge_drive
r
    self.merge_update_state(MERGE_INFO_CONTENTS)
  File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_prog_lcfit.py", line 1329, in merge_upda
te_state
    job_stats = self.get_job_stats(script_dir,
  File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_prog_base.py", line 2425, in get_job_sta
ts
    job_stats[key_list][isplit] = stats_yaml[key]
KeyError: 'NEVT_LC_CUTS'
'NEVT_LC_CUTS'
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/submit_batch/submit_batch_jobs.py", line 416, in run_
merge_driver
    program.merge_driver()
  File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_prog_base.py", line 1449, in merge_drive
r
    self.merge_update_state(MERGE_INFO_CONTENTS)
  File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_prog_lcfit.py", line 1329, in merge_upda
te_state
    job_stats = self.get_job_stats(script_dir,   File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_prog_base.py", line 2425, in get_job_stats
    job_stats[key_list][isplit] = stats_yaml[key]
KeyError: 'NEVT_LC_CUTS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/submit_batch/submit_batch_jobs.py", line 475, in <module>
    run_merge_driver(program,args)
  File "/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/submit_batch/submit_batch_jobs.py", line 428, in run_merge_driver
    program.log_assert(False, msg )
  File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_prog_base.py", line 2493, in log_assert
    util.log_assert(condition, msgerr)        
  File "/global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util/submit_batch/submit_util.py", line 1223, in log_assert
    assert condition, msg_abort_face
AssertionError: 
```

excerpt from file : 
`FIT_DATA_SPECZ_LSST_SIMDATA/output/SPLIT_JOBS_LCFIT/CPU0008_JOBLIST_login09.LOG`

**Comment by RickKessler** [comment]
Fixed two silly bugs introduced in minor refactor for BayeSN compatibilty.
