### ISSUE TITLE
GENTYPE AGN is causing a seg fault during SIMnorm

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1318]
During SIMnorm, I get the following segfault. Outputs can be found in `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/ROMAN_PLAsTiCC_AGN` and the segfault can be found in `PIP_*AGN.LOG.`

```
 Program class : Simulation

 Submit host;  midway2-login2
 Program name: snlc_sim.exe
         Batch command:    sbatch
         Batch template:   /project2/rkessler/PRODUCTS/SNANA/SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE
         Batch n_core:     1
 Create output dir:
   /scratch/midway2/rkessler/PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/ROMAN_PLAsTiCC_AGN/LOGS
         Copy 3 sim-input files to LOGS
 sim_prep_GENOPT(PIP_PIPPIN_ROMAN_TRANS_ROMAN_PLAsTiCC_AGN)
         GENOPT(simgen_AGN.input): GENRANGE_REDSHIFT 0.03  2.9     HOSTLIB_FILE $SNANA_ROMAN_ROOT/starterKits/sim_host_redshift/3dhst_sim_input_cat_v1.7.hostlib
  FORMAT_MASK = 48 (<built-in function format>)

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f26dba6746c in waitpid () from /lib64/libc.so.6
#1  0x00007f26db9e4f62 in do_system () from /lib64/libc.so.6
#2  0x00007f26e0150e59 in TUnixSystem::StackTrace() () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#3  0x00007f26e0152a5c in TUnixSystem::DispatchSignals(ESignals) () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#4  <signal handler called>
#5  0x00007f26dba381cf in __rawmemchr_sse2 () from /lib64/libc.so.6
#6  0x00007f26dba20a92 in _IO_str_init_static_internal () from /lib64/libc.so.6
#7  0x00007f26dba0e6d7 in __isoc99_vsscanf () from /lib64/libc.so.6
#8  0x00007f26dba0e677 in __isoc99_sscanf () from /lib64/libc.so.6
#9  0x000000000040fe80 in parse_input_TAKE_SPECTRUM ()
#10 0x00000000004108f7 in parse_input_SPECTRUM ()
#11 0x000000000043e025 in parse_input_key_driver ()
```

**Comment by RickKessler** [comment]
I think I had already fixed this problem, but forgot to update Midway ... after updating Midway, the SIMnorm job runs.
