### ISSUE TITLE
snana.exe NOFILE command [SegFault]

### ISSUE THREAD

**Issue by BrunoSanchez** [RickKessler/SNANA#1367]
Command `snana.exe` ran in midway machine failed with following setup:

To reproduce a table first is needed: 

```midway2-login1 REWRITE_BRUNO_JUN2024 > snana.exe NOFILE \
  VERSION_PHOTOMETRY    DESALL_forcePhoto_real_snana_fits \
   PRIVATE_DATA_PATH     $DES_ROOT/lcmerge \
   PRIVATE_CUTWIN_STRING  'DES_transient_status 1 999' \
   SNTABLE_LIST SNANA \
   TEXTFILE_PREFIX OUT_DES_SNANA_TABLE \
                 > OUT_DES_SNANA_TABLE.LOG
```

The command that fails is the following:
```
midway2-login1 REWRITE_BRUNO_JUN2024 > snana.exe NOFILE \
   VERSION_PHOTOMETRY        DES5YR_SMP \
   PRIVATE_DATA_PATH         $DES_ROOT/lcmerge \
   VERSION_REFORMAT_FITS     DES-SN5YR_DES \
   SNCID_LIST_FILE    OUT_DES_SNANA_TABLE.SNANA.TEXT \
   PRIVATE_VARNAME_READLIST  AGN_SCAN \
   PHOTFLAG_DETECT    4096  \
   PHOTFLAG_TRIGGER  16384 \
   HEADER_OVERRIDE_FILE  override_DES_hostgal_complete_ur.dat \
   TEXTFILE_PREFIX OUT_DES_REWRITE \
                 > OUT_DES_REWRITE.LOG
```
Result of program: 

```Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7ffb20cca3ff in ???
#1  0x7ffb20d02044 in ???
#2  0x4c85fb in ???
#3  0x423c37 in ???
#4  0x46f5ff in ???
#5  0x405e8e in ???
#6  0x7ffb20cb6554 in ???
#7  0x406137 in ???
#8  0xffffffffffffffff in ???
Segmentation fault (core dumped)
```

**Comment by BrunoSanchez** [comment]
As a brief addition, this is reproduced using a single CID instead of list of them in a file.

**Comment by RickKessler** [comment]
it ran fine for me; see $SNANA_DEBUG/Bruno
and RUNSTEP1.sh and RUNSTEP2.sh

**Comment by BrunoSanchez** [comment]
Solved. Thanks
