### ISSUE TITLE
Segfault when fitting LCs

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1381]
Hello! Trying to fit some light curves, and I'm running into a segfault error :(

/scratch/midway2/rkessler/PIPPIN_OUTPUT/DOVEKIE/2_LCFIT/DESFIT_DATADES/output/SPLIT_JOBS_LCFIT

/scratch/midway2/rkessler/PIPPIN_OUTPUT/DOVEKIE/2_LCFIT/DESFIT_DATADES/output/SPLIT_JOBS_LCFIT/FAIL_SUMMARY.LOG 

```
 ******************************************************************
   RD_OVERRIDE_INIT

Program received signal SIGSEGV: Segmentation fault - invalid memory referenc\
e.

Backtrace for this error:
#0  0x7f78ea6f73ff in ???
#1  0x7f78ea72f0d4 in ???
```

**Comment by bap37** [comment]
With Rick's help, figured it out, was pointing to files that didn't exist
