### ISSUE TITLE
Crash during snlc_fit.exe execution

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1428]
When running a LSST  fitting I got this crash message:

```
At line 548369 of file ../src/snlc_fit.f
Fortran runtime error: Index '2001' of dimension 1 of array 'i4ep_all' above upper bound of 2000

Error termination. Backtrace:
#0  0x55e548fe4572 in load_epall__
	at ../src/snlc_fit.f:548369
#1  0x55e549022a55 in fitini_cov__
	at ../src/snlc_fit.f:544957
#2  0x55e549019b21 in fitpar_prep__
	at ../src/snlc_fit.f:421185
#3  0x55e548fd971b in snana_driver__
	at ../src/snlc_fit.f:94997
#4  0x55e548f604fa in exec_read_data__
	at ../src/snlc_fit.f:12057
#5  0x55e548f5faa0 in process_data_version__
	at ../src/snlc_fit.f:54332
#6  0x55e54908688a in snana
	at ../src/snlc_fit.f:2302
#7  0x55e5490869bf in main
	at ../src/snlc_fit.f:2325
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class TH1F is available even though it has a TClass initialization routine.
```

This look as it is related to a too many epoch problem?

This can be reproduced on NERSC using:
```
snlc_fit.exe /global/homes/b/bastienc/MY_SNANA_DIR/LSST_SNANA/PaperBBCVpec/debug/fit_cfg_debug.nml  VERSION_PHOTOMETRY PIP_LSST_UCHUU_MOCK07_BBC_BC_LSST_RNDSMEAR_BBC JOBSPLIT 10 30      TEXTFILE_PREFIX DEBUG ROOTFILE_OUT DEBUG.ROOT CUTWIN_CID 6761907, 6770000
```

**Comment by bastiencarreres** [comment]
Seems to be solved by reducing number of obs in LIBID
