### ISSUE TITLE
Unable to run create_covariance.py 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1456]
Hello! 

I am no longer able to run create_covariance.py due to missing matplotlib requirements in python 

```
(base) [bap37@midway2-login1 SCRIPTS_COVMAT]$ ./FAIL_REPEAT_COVMAT_ALL_DATA_DATA_OUTPUT_BBCFIT.CMD
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 144, in <module>
    import seaborn as sb
  File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/seaborn/__init__.py", line 8, in <module>
    from .distributions import *  # noqa: F401,F403
  File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/seaborn/distributions.py", line 23, in <module>
    from ._stats.counting import Hist
  File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/seaborn/_stats/counting.py", line 10, in <module>
    from seaborn._core.scales import Scale
  File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/seaborn/_core/scales.py", line 28, in <module>
    from matplotlib.dates import (
ImportError: cannot import name 'ConciseDateFormatter' from 'matplotlib.dates' (/home/bap37/.local/lib/python3.7/site-packages/matplotlib/dates.py)
```

error can be replicated here:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/DOJOKIE/7_CREATE_COV/ALL_DATA/output/SCRIPTS_COVMAT

**Comment by RickKessler** [comment]
your task works fine for me so I suspect that you have something in your environment that conflicts with 
source $PRODUCTS/SNANA/SNANA_setup.sourceme conda

**Comment by bap37** [comment]
After deactivating conda repeatedly to get to the base environment, then performing 
`source $PRODUCTS/SNANA/SNANA_setup.sourceme conda` and immediately running the code, I still get the same error
