### ISSUE TITLE
SALT2mu With Ranseed Change Sims Segfault

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#295]
`source $SNANA_DEBUG/djbrout/segfault/RUNTEST`
will result in a segfaul. you can kill the script once you see the segfault cause it will keep trying to run if you let it go

**Comment by djbrout** [comment]
Here is the log
``` Program class : BBC 

 Program name: SALT2mu.exe
	 Batch command:  sbatch
	 Batch template: /project2/rkessler/PRODUCTS/SNANA/SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE
	 Batch n_core:   1
 Create output dir:
   /project2/rkessler/PRODUCTS/SNANA_DEBUG/djbrout/segfault/SALT2mu

 Store 0 BBC options from MUOPT keys
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_HFITdatawithsys_SIMDATAHST_G10/output
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_CFITdatawithsys_SIMDATACALIB_G10/output
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_LFITdatawithsys_SIMDATALOWZ_G10/output
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_DFITdatawithsys_SIMDATADES_G10/output
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_PFITdatawithsys_SIMDATAPS1_G10/output
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_SDFITsimdatawithsys_SIMDATASIMSDSS_G10/output
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_SNFITsimdatawithsys_SIMDATASIMSNLS_G10/output
  Prepare INPDIR /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_FFITdatawithsys_SIMDATAFOUNDBIG_G10/output
  STRINGMATCH_IGNORE = IGNORE -> Attempt auto-match version(s) in each INPDIR
  Auto-match success: one split-sim version (from RANSEED_CHANGE) per INPDIR

 Prepare output FITOPT list:
   Found  15 FITOPTs for SURVEY = PS1_HST_COMBINED
   Found  15 FITOPTs for SURVEY = DES3YR_LOWZ_COMBINED
   Found  73 FITOPTs for SURVEY = PS1_LOWZ_COMBINED
   Found  23 FITOPTs for SURVEY = DES
   Found  23 FITOPTs for SURVEY = PS1MD
   Found  25 FITOPTs for SURVEY = SDSS
   Found  23 FITOPTs for SURVEY = SNLS
   Found  21 FITOPTs for SURVEY = FOUNDATION
   Found FITOPT_MAP  
   --> 1 output FITOPTs
  FITOPTxMUOPT logic: process only FITOPT=0 or MUOPT=0 

  Create BBC output directories:
    Create BBC output dir OUTPUT_BBCFIT-0001 
    Create BBC output dir OUTPUT_BBCFIT-0002 
    Create BBC output dir OUTPUT_BBCFIT-0003 
    Create BBC output dir OUTPUT_BBCFIT-0004 
    Create BBC output dir OUTPUT_BBCFIT-0005 
    Create BBC output dir OUTPUT_BBCFIT-0006 
    Create BBC output dir OUTPUT_BBCFIT-0007 
    Create BBC output dir OUTPUT_BBCFIT-0008 
    Create BBC output dir OUTPUT_BBCFIT-0009 
    Create BBC output dir OUTPUT_BBCFIT-0010 

  Prepare input FITRES files

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fc13deeb45c in waitpid () from /lib64/libc.so.6
#1  0x00007fc13de68f52 in do_system () from /lib64/libc.so.6
#2  0x00007fc142638e59 in TUnixSystem::StackTrace() () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#3  0x00007fc14263aa5c in TUnixSystem::DispatchSignals(ESignals) () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#4  <signal handler called>
#5  0x000000000041dab0 in compute_more_INFO_DATA ()
#6  0x000000000042a9b5 in SALT2mu_DRIVER_INIT ()
#7  0x000000000042b783 in main ()
===========================================================

```

**Comment by RickKessler** [comment]
fixed.
