### ISSUE TITLE
submit_batch_jobs issue

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#301]
`source $SNANA_DEBUG/djbrout/sdss/RUNTEST`

```	 pid = 7069853 for FIT_PIP_PLUS_SIMSDSS_5D_C11.nml-CPU0017
	 pid = 7069854 for FIT_PIP_PLUS_SIMSDSS_5D_C11.nml-CPU0018
	 pid = 7069855 for FIT_PIP_PLUS_SIMSDSS_5D_C11.nml-CPU0019
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 416, in <module>
    program.launch_jobs() # submit via batch or ssh
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 614, in launch_jobs
    self.fetch_slurm_pid_list()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 670, in fetch_slurm_pid_list
    j_job    = pid_all.index(job_name)
ValueError: 'FIT_PIP_PLUS_SIMSDSS_5D_C11.nml-CPU0020' is not in list
```

**Comment by RickKessler** [comment]
there are 83 djbrout jobs in the broadwl-lc queue and limit is 100. So after 17 more jobs, the jobs are not launched and submit_batch cannot recover the pid.  I will try to trap these errors and gracefully report the number of unsubmitted jobs.

**Comment by RickKessler** [comment]
improved error messaging when jobs don't get into queue.
