### ISSUE TITLE
MERGE Crash (list index out of range)

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#358]
Note that this is a different issue to #349 

Affects both `$PIPPIN_OUTPUT/PA_SIM_REALSYSC11_3YR` and `$PIPPIN_OUTPUT/PA_SIM_REALFITOPTC11_3YR`

Sim merging crashes at merge stage with

`# FATAL ERROR ABORT`
`#    list index out of range`
`#    Check CPU0015*.LOG for merge crash`

in `MERGE.LOG` and in `CPU0015*.LOG`:

```12 [IndexError('list index out of range'), 'Check CPU0015*.LOG for merge crash']
 13 Traceback (most recent call last):
 14   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs    .py", line 379, in <module>
 15     program.merge_driver()
 16   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.    py", line 830, in merge_driver
 17     self.merge_update_state(MERGE_INFO_CONTENTS)
 18   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.p    y", line 1755, in merge_update_state
 19     NSPLIT       = row[COLNUM_NSPLIT]
 20 IndexError: list index out of range
 21 Traceback (most recent call last):
 22   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs    .py", line 379, in <module>
 23     program.merge_driver()
 24   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.    py", line 830, in merge_driver
 25     self.merge_update_state(MERGE_INFO_CONTENTS)
 26   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.p    y", line 1755, in merge_update_state
 27     NSPLIT       = row[COLNUM_NSPLIT]
 28 IndexError: list index out of range

**Comment by RickKessler** [comment]
I can't find the error; please give full path file(s) with errors.

**Comment by OmegaLambda1998** [comment]
Fixed - was a Pippin error which got resolved
