### ISSUE TITLE
submit_batch_jobs.sh and PIPPIN failing

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#374]
Working with Dan Scolnic and Brodie Popovic.

Running `submit_batch_jobs.sh plus_erik.input --ignore_fitopt` 
(which can be done in `$SNANA_DEBUG/epeterson3`)

I get this error message on my first attempt:
``` Write FAIL to done stamp file: 
	 ALL.DONE
['1 of 48 jobs NOT in queue.', 'Check for sbatch problem; e.g., njob limit.']
NoneType: None
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 432, in <module>
    program.launch_jobs() # submit via batch or ssh
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 685, in launch_jobs
    self.fetch_slurm_pid_list()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 759, in fetch_slurm_pid_list
    self.log_assert(False, msgerr)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 1672, in log_assert
    util.log_assert(condition, msgerr)        
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 916, in log_assert
    assert condition, msg_abort_face
AssertionError: 
   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
FATAL ERROR ABORT : 
   1 of 48 jobs NOT in queue.
   Check for sbatch problem; e.g., njob limit.
```

Upon my second attempt, the jobs run successfully, but fail instantly.

Brodie has experienced a similar issue using PIPPIN.

Additionally, upon typing the command:
`SALT2mu.exe`

I receive:
```SALT2mu.exe: /lib64/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by SALT2mu.exe)```

**Comment by RickKessler** [comment]
when a job fails immediately, it can drop out of the queue before the NPID test and thus fails the NPID test.  The SALT2mu.exe failure is fixed, but your MUOPT used datafile_override without a path, and thus it failed again. I included a path and it's working.
