### ISSUE TITLE
Segmentation violation when simulating MW dust

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#404]
I was trying to generate several LSST WFD  simulations using various cadences.
Something strange started happening with the WFD in particular and with the largest jobs in particular.
at a certain point the simulation crashes with this error:

```
...
	 Finished generating  1511000 of 1611848 (CID=93565141) 
	 Finished generating  1511500 of 1611848 (CID=69169691) 
	 Finished generating  1512000 of 1611848 (CID=148153958) 
	 Finished generating  1512500 of 1611848 (CID=55444515) 
	 Finished generating  1513000 of 1611848 (CID=88503405) 

 *** Break *** segmentation violation
ERROR: Error opening file: /global/cfs/cdirs/lsst/groups/SN/snana/SNDATA_ROOT/MWDUST/SFD_dust_4096_sgp.fits



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002aaaafb3e2ba in waitpid () from /lib64/libc.so.6
#1  0x00002aaaafabb86f in do_system () from /lib64/libc.so.6
#2  0x00002aaaab745823 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x1041cb80) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:2106
#3  TUnixSystem::StackTrace (this=0x1041cb80) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:2400
#4  0x00002aaaab748064 in TUnixSystem::DispatchSignals (this=0x1041cb80, sig=kSigSegmentationViolation) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:3631
#5  <signal handler called>
#6  0x00002aaaafaeff81 in getc () from /lib64/libc.so.6
#7  0x00000000004bc7e9 in fits_get_next_card_ ()
#8  0x00000000004be549 in fits_read_fits_header_ ()
#9  0x00000000004bfbe0 in fits_read_file_fits_header_only_ ()
#10 0x00000000004c040d in lambert_getval ()
#11 0x00000000004c0e42 in MWgaldust ()
#12 0x00000000004c0efd in modify_MWEBV_SFD ()
#13 0x00000000004100b1 in gen_MWEBV ()
#14 0x0000000000421672 in gen_event_driver ()
#15 0x000000000043e697 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002aaaafaeff81 in getc () from /lib64/libc.so.6
#7  0x00000000004bc7e9 in fits_get_next_card_ ()
#8  0x00000000004be549 in fits_read_fits_header_ ()
#9  0x00000000004bfbe0 in fits_read_file_fits_header_only_ ()
#10 0x00000000004c040d in lambert_getval ()
#11 0x00000000004c0e42 in MWgaldust ()
#12 0x00000000004c0efd in modify_MWEBV_SFD ()
#13 0x00000000004100b1 in gen_MWEBV ()
#14 0x0000000000421672 in gen_event_driver ()
#15 0x000000000043e697 in main ()
===========================================================


```

or similarly but with the file `SFD_dust_4096_ngp.fits` instead of `SFD_dust_4096_sgp.fits`
```
 *** Break *** segmentation violation
ERROR: Error opening file: /global/cfs/cdirs/lsst/groups/SN/snana/SNDATA_ROOT/MWDUST/SFD_dust_4096_ngp.fits



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002aaaafb3e2ba in waitpid () from /lib64/libc.so.6
#1  0x00002aaaafabb86f in do_system () from /lib64/libc.so.6
#2  0x00002aaaab745823 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x1041cb80) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:2106
#3  TUnixSystem::StackTrace (this=0x1041cb80) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:2400
#4  0x00002aaaab748064 in TUnixSystem::DispatchSignals (this=0x1041cb80, sig=kSigSegmentationViolation) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:3631
#5  <signal handler called>
#6  0x00002aaaafaeff81 in getc () from /lib64/libc.so.6
#7  0x00000000004bc7e9 in fits_get_next_card_ ()
#8  0x00000000004be549 in fits_read_fits_header_ ()
#9  0x00000000004bfbe0 in fits_read_file_fits_header_only_ ()
#10 0x00000000004c040d in lambert_getval ()
#11 0x00000000004c0e42 in MWgaldust ()
#12 0x00000000004c0efd in modify_MWEBV_SFD ()
#13 0x00000000004100b1 in gen_MWEBV ()
#14 0x0000000000421672 in gen_event_driver ()
#15 0x000000000043e697 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002aaaafaeff81 in getc () from /lib64/libc.so.6
#7  0x00000000004bc7e9 in fits_get_next_card_ ()
#8  0x00000000004be549 in fits_read_fits_header_ ()
#9  0x00000000004bfbe0 in fits_read_file_fits_header_only_ ()
#10 0x00000000004c040d in lambert_getval ()
#11 0x00000000004c0e42 in MWgaldust ()
#12 0x00000000004c0efd in modify_MWEBV_SFD ()
#13 0x00000000004100b1 in gen_MWEBV ()
#14 0x0000000000421672 in gen_event_driver ()
#15 0x000000000043e697 in main ()
===========================================================


```
Full LOG files can be found here:
`/global/homes/m/mvincenz/desc/inputs/SIMLOGS_LSSTWFDSF/TMP_mvin_MV_LSSTWFDSF_SNIbc-V19_NONIaMODEL0-0004_54510.LOG
`
or here
`/global/homes/m/mvincenz/desc/inputs/SIMLOGS_LSSTWFDF8/TMP_mvin_MV_LSSTWFDF8_SNII-V19_NONIaMODEL0-0012_33100.LOG 
`
This seems to be related to the simulation of Milky Way extinction. But I'm not sure what's happening. 
Unfortunately, the error generally happens towards the end of large WFD sims (never seen this when simulating DDF). So, lots of CPU hours wasted because the simulation crashes when it is almost done. The error doesn't show up when I do smaller tests, so I'm struggling to debug.

Thanks!!

**Comment by maria-vincenzi** [comment]
I just rerun the same simulation (without changing anything) and this time it didn't crash.
So all good!
