### ISSUE TITLE
Segmentation fault in lcfitting

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#411]
Got a segmentation fault in lcfitting.
logs at `$WFIRST_USERS/mdai/SALT3_training_tests/all_tests/train_no_old_lowz_1dbiascor/LOWZ_COMBINED_LC_201`

```
   Open SIM_SALT3TRAIN_201_SNIaMODEL0-0001_SPEC.FITS  
   Read 962 wavelength bins.
   Read 340 SPECTRUM-HEADER rows.
    Process SPLIT-JOB   1 of   5

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7FA13DDF2697
#1  0x7FA13DDF2CDE
#2  0x7FA13CFE63EF
#3  0x52B486 in RD_SNFITSIO_SPECDATA
#4  0x52DF66 in RD_SNFITSIO_EVENT
#5  0x52DFE5 in rd_snfitsio_event__
#6  0x4CFAE1 in exec_read_data__
#7  0x4CFB9B in process_data_version__
./FAIL_REPEAT_SALT3TRAIN_LOWZ_201_FITOPT000_SPLIT001.CMD: line 5:  1506 Segmentation fault      snlc_fit.exe LOWZ_COMBINED.NML.temp.1614824150.9325747_201 VERSION_PHOTOMETRY SALT3TRAIN_LOWZ_201 JOBSPLIT 1 5 TEXTFILE_PREFIX SALT3TRAIN_LOWZ_201_FITOPT000_SPLIT001
```

**Comment by RickKessler** [comment]
another dumb bug related to events that have no spectra; fixed.
