### ISSUE TITLE
Weird LCFit Merge Issue

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#459]
```
cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_7DSIMS/2_LCFIT/PFITnosys_SIMPS1_4D_BS20
source RUNME
```

produces the following error

```
submit_batch_jobs.sh FIT_PIP_PLUS_7DSIMS_SIMPS1_4D_BS20.nml  --merge
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 386, in <module>
    program.merge_driver()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 802, in merge_driver
    cpunum      = self.config_yaml['args'].cpunum[0]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 386, in <module>
    program.merge_driver()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 802, in merge_driver
    cpunum      = self.config_yaml['args'].cpunum[0]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 391, in <module>
    cpunum   = config_yaml['args'].cpunum[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by RickKessler** [comment]
the main problem is that the text-append for the large biasCor took more than the allocated 2GB of memory ... so need to increase with something like
BATCH_MEM:  4000 
I also noticed a few Pippin issues
1)  the following invalid line is somehow added under the CONFIG block,
    '!': FITRES RA DEC TGAPMAX TrestMIN  TrestMAX
    (seems to have done no harm, but would be prudent to fix this on Pippin side)
2) For the large biasCor LCFIT jobs, it would be safer to remove APPEND_TABLE_VARLIST from CONFIG block. I don't think these appended variables serve any purpose in the biasCor, and it just takes extra resources and time for nothing.
