### ISSUE TITLE
Error with create_covariance module for generating covariance matrix

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#499]
I am trying to generate covariance matrix data for feeding into cosmomc (or MontePython), using the `create_covariance.py` module. I am getting key errors.  I am using simulated PLAsTiCC data. 

After the BBC correction, I invoke the create_covariance program to be run on the BBC corrected output data, from it's directory. This is done by giving an information file as an argument input to the `create_covariance.py`, which lists all the necessary input details.  
The syntax is below : 

`pwd`

`...XYZ/OUT_BBC5D`

`create_covariance.py ./OUTPUT_BBCFIT.input `

Results in the following errors :

`[    INFO | create_covariance.py:949]   # ========== BEGIN create_covariance ===============
[    INFO | create_covariance.py:889]   Read Hubble diagrams for version = LSST_DDF_MODEL11
[   ERROR | create_covariance.py:955]   'FITOPT001_MUOPT000'
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/create_covariance.py", line 953, in <module>
    create_covariance(config, args)
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/create_covariance.py", line 895, in create_covariance
    muopt_labels, muopt_scales, extracovdict)
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/create_covariance.py", line 506, in get_contributions
    df_compare = m0difs[get_name_from_fitopt_muopt(f, 0)]
KeyError: 'FITOPT001_MUOPT000'
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/create_covariance.py", line 956, in <module>
    raise e
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/create_covariance.py", line 953, in <module>
    create_covariance(config, args)
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/create_covariance.py", line 895, in create_covariance
    muopt_labels, muopt_scales, extracovdict)
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/create_covariance.py", line 506, in get_contributions
    df_compare = m0difs[get_name_from_fitopt_muopt(f, 0)]
KeyError: 'FITOPT001_MUOPT000'
`

The `OUTPUT_BBCFIT.info` file is shown below : 

`CALIBRATORS: []
COSMOMC_TEMPLATES: /global/cfs/cdirs/desc-sn/pippin/data_files/cosmomc_templates
COVOPTS:
- '[NOSYS]  [=DEFAULT,=DEFAULT]'
- '[DC2CAL] [+DC2CAL,=DEFAULT]'
- '[MWEBV]  [=MWEBV,=DEFAULT]'
DATASET_FILE: dataset.txt
EXTRA_COVS: []

INPUT_DIR: /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/ayanmitr/plasticc_SNIa_cosmology/OUT_BBC5D

MUOPT_SCALES: {}
#NAME: LSST_COV_BBC_DC2DATA
NAME: LSST_COV_BBC_PSTDATA

OUTDIR: /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/ayanmitr/plasticc_SNIa_cosmology/LSST_COV_BBC_PSTDATA/output

SYSFILE: /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/ayanmitr/plasticc_SNIa_cosmology/LSST_COV_BBC_PSTDATA/sys_scale.yml

VERSION: LSST_DDF_MODEL11

#END_YAML
`

**Comment by RickKessler** [comment]
tutorial was not appropriate for systematics; use Pippin instead.
