### ISSUE TITLE
Run SNANA simulations fail

### ISSUE THREAD

**Issue by Catarina-Alves** [RickKessler/SNANA#604]
I run SNANA simulations similar to PLAsTiCC for DDF. I follow the same process as I did before but I now it fails. I am running this from `/global/homes/c/catarina/simulations/baseline_nexp2_v1.7_10yrs`.

```
$ submit_batch_jobs.sh SIMGEN_MASTER_LSST_DDF.INPUT --fast

 Program class : Simulation 

 Program name: snlc_sim.exe
	 Batch command:  sbatch
	 Batch template: /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/SBATCH_TEMPLATES/SBATCH_Cori.TEMPLATE
	 Batch n_core:   10
 Create output dir:
   /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF

 sim_prep_GENOPT(LSST_DDF_MODEL67_SNIa-91bg) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL52_SNIax) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIax.INPUT     GENTYPE 52     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL95_SLSN-I) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SLSN-I-MOSFIT.INPUT     GENTYPE 95     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL42_SNIIn) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIIn-MOSFIT.INPUT     GENTYPE 42     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL62_SNIbc-MOSFIT) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIbc-MOSFIT.INPUT     GENTYPE 62     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL42_SNII-NMF) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNII-NMF.INPUT     GENTYPE 42     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL42_V19_CC+HostXT) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_V19_CC+HostXT.INPUT     GENTYPE 42     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL42_SNII-Templates) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNII-Templates.INPUT     GENTYPE 42     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL62_SNIbc-Templates) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIbc-Templates.INPUT     GENTYPE 62     SEARCHEFF_SPEC_SCALE 1.0     
 sim_prep_GENOPT(LSST_DDF_MODEL90_SNIa-SALT2) 
	 GENOPT(SIMGEN_TEMPLATE_LSST.INPUT): INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-SALT2.INPUT     GENTYPE 90     SEARCHEFF_SPEC_SCALE 0.5     
  FORMAT_MASK = 48 (<built-in function format>) 

 Write FAIL to done stamp file: 
	 ALL.DONE
['Unable to find NGENTOT_RATECALC: key in SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG ;', 'LOG created from sim normalization commands :', '  cd /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF ;  \\', '  snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT  \\', '  INIT_ONLY 1 INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0      SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/baseline_nexp2_v1.7_10yrs_DDF.simlib.COADD  SOLID_ANGLE 0.028634308040531967   PATH_USER_INPUT /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs   \\', '  > SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG \\']
NoneType: None



   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF ;  \
     snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT  \
     INIT_ONLY 1 INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0      SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/baseline_nexp2_v1.7_10yrs_DDF.simlib.COADD  SOLID_ANGLE 0.028634308040531967   PATH_USER_INPUT /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs   \
     > SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG \
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/submit_batch/submit_batch_jobs.py", line 432, in <module>
    program.submit_prepare_driver()
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 172, in submit_prepare_driver
    self.sim_prep_NGENTOT_LC()
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 563, in sim_prep_NGENTOT_LC
    ngentmp = self.get_ngentot_from_rate(iver,ifile)
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 723, in get_ngentot_from_rate
    self.log_assert(False,msgerr)
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_base.py", line 1804, in log_assert
    util.log_assert(condition, msgerr)
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_util.py", line 903, in log_assert
    assert condition, msg_abort_face
AssertionError: 


   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF ;  \
     snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT  \
     INIT_ONLY 1 INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0      SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/baseline_nexp2_v1.7_10yrs_DDF.simlib.COADD  SOLID_ANGLE 0.028634308040531967   PATH_USER_INPUT /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs   \
     > SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG \

 Write FAIL to done stamp file: 
	 ALL.DONE
[AssertionError("\n\n\n   `|```````|`    \n   <| o\\ /o |>   \n    | ' ; ' |     \n    |  ___  |     ABORT submit on Fatal Error. \n    | |' '| |     \n    | `---' |     \n    \\_______/    \n\nFATAL ERROR ABORT : \n   Unable to find NGENTOT_RATECALC: key in SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG ;\n   LOG created from sim normalization commands :\n     cd /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF ;  \\\n     snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT  \\\n     INIT_ONLY 1 INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0      SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/baseline_nexp2_v1.7_10yrs_DDF.simlib.COADD  SOLID_ANGLE 0.028634308040531967   PATH_USER_INPUT /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs   \\\n     > SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG \\"), 'Crashed while preparing batch jobs.', 'Check Traceback']
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/submit_batch/submit_batch_jobs.py", line 432, in <module>
    program.submit_prepare_driver()
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 172, in submit_prepare_driver
    self.sim_prep_NGENTOT_LC()
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 563, in sim_prep_NGENTOT_LC
    ngentmp = self.get_ngentot_from_rate(iver,ifile)
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 723, in get_ngentot_from_rate
    self.log_assert(False,msgerr)
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_base.py", line 1804, in log_assert
    util.log_assert(condition, msgerr)
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_util.py", line 903, in log_assert
    assert condition, msg_abort_face
AssertionError: 


   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF ;  \
     snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT  \
     INIT_ONLY 1 INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0      SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/baseline_nexp2_v1.7_10yrs_DDF.simlib.COADD  SOLID_ANGLE 0.028634308040531967   PATH_USER_INPUT /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs   \
     > SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG \
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/submit_batch/submit_batch_jobs.py", line 432, in <module>
    program.submit_prepare_driver() 
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 172, in submit_prepare_driver
    self.sim_prep_NGENTOT_LC()
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 563, in sim_prep_NGENTOT_LC
    ngentmp = self.get_ngentot_from_rate(iver,ifile) 
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_sim.py", line 723, in get_ngentot_from_rate
    self.log_assert(False,msgerr)
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_base.py", line 1804, in log_assert
    util.log_assert(condition, msgerr)        
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_util.py", line 903, in log_assert
    assert condition, msg_abort_face
AssertionError: 


   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF ;  \
     snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT  \
     INIT_ONLY 1 INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0      SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/baseline_nexp2_v1.7_10yrs_DDF.simlib.COADD  SOLID_ANGLE 0.028634308040531967   PATH_USER_INPUT /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs   \
     > SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG \

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/submit_batch/submit_batch_jobs.py", line 449, in <module>
    program.log_assert(False, msg )
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_prog_base.py", line 1804, in log_assert
    util.log_assert(condition, msgerr)        
  File "/global/cfs/cdirs/snana/SNANA/util/submit_batch/submit_util.py", line 903, in log_assert
    assert condition, msg_abort_face
AssertionError: 


   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   


   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs/SIMLOGS_CSA_LSST_DDF ;  \
     snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT  \
     INIT_ONLY 1 INPUT_FILE_INCLUDE $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_SNIa-91bg.INPUT     GENTYPE 67     SEARCHEFF_SPEC_SCALE 1.0      SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/baseline_nexp2_v1.7_10yrs_DDF.simlib.COADD  SOLID_ANGLE 0.028634308040531967   PATH_USER_INPUT /global/u1/c/catarina/simulations/baseline_nexp2_v1.7_10yrs   \
     > SIMnorm_LSST_DDF_MODEL67_SNIa-91bg_NONIaMODEL0.LOG \
   Crashed while preparing batch jobs.
   Check Traceback
```

**Comment by RickKessler** [comment]
DOCUMENTATION block must be at top of the file.
