### ISSUE TITLE
SALT2 train missing model_covmat_for_error_snake.fits 

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#628]
```
DEBUG FunctionBasis::~FunctionBasis()
cannot open full_weight_1.fits
INFO training_sample    = trainingsample_snls_sdss_v5.list
INFO configuration file = training_without_error_snake.conf
INFO pca file           = pca_1_opt1_final.list
INFO weight matrix      = full_weight_1.fits
INFO cov    matrix      = covmat_1_with_constraints.fits
FATAL ERROR cannot read file full_weight_1.fits
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/snpca/train_SALT2.py", line 196, in <module>
    train_SALT2(options)
  File "/project2/rkessler/PRODUCTS/snpca/train_SALT2.py", line 107, in train_SALT2
    sh.copy('model_covmat_for_error_snake.fits','model_covmat_for_error_snake_first.fits')
  File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'model_covmat_for_error_snake.fits'
```

**Comment by RickKessler** [comment]
this is related to your recently modified CALIB_PATH
