### ISSUE TITLE
Key Error NGENTOT_LC

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#645]
Output directory: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/CODETEST/1_SIM/BIASCOR_LOWZSIMBIAS_G10`

Error:
```
Traceback (most recent call last):
 File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 435, in     <module>
 program.submit_prepare_driver()
 File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 174, in su    bmit_prepare_driver
 self.sim_prep_NGENTOT_LC()
 File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 565, in si    m_prep_NGENTOT_LC
 dummy   = self.get_ngentot_from_input(iver,ifile,-1)
 File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 607, in ge    t_ngentot_from_input
 ngentot  = INFILE_KEYS[iver][ifile][KEY_NGENTOT]
 KeyError: 'NGENTOT_LC'
```

**Comment by RickKessler** [comment]
silly bug from fix earlier tonight . Try again.
