### ISSUE TITLE
segmentation violation in BBC

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#752]
BBC crashing after loading the CC prior file.

```
	 Found 90371 events in /scratch/midway2/rkessler/PIPPIN_OUTPUT/DES5YR_5YRBC/5_MERGE/MERGE_DCCPRIOR_DESSIMBIAS5YRCC_V19/output/PIP_MV_GLOBAL_BIASCOR_DESSIMBIAS5YRCC_V19/FITOPT000.FITRES.gz. 
	 malloc_INFO_CCPRIOR: 103.215 MB 
   OPEN_TEXTFILE: /scratch/midway2/rkessler/PIPPIN_OUTPUT/DES5YR_5YRBC/5_MERGE/MERGE_DCCPRIOR_DESSIMBIAS5YRCC_V19/output/PIP_MV_GLOBAL_BIASCOR_DESSIMBIAS5YRCC_V19/FITOPT000.FITRES.gz 
   Read 81 table varNames from TEXT table=FITRES 
	 Prepare read-variable 'CID' (ivar=0, CAST=C) 
...
...
	 ==> Finished reading 32 of 81 variables with 90371 entries
	 Force pIa=1.0 for 0 events from /scratch/midway2/rkessler/PIPPIN_OUTPUT/DES5YR_5YRBC/5_MERGE/MERGE_DCCPRIOR_DESSIMBIAS5YRCC_V19/output/PIP_MV_GLOBAL_BIASCOR_DESSIMBIAS5YRCC_V19/FITOPT000.FITRES.gz

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fbe199cf45c in waitpid () from /lib64/libc.so.6
#1  0x00007fbe1994cf52 in do_system () from /lib64/libc.so.6
#2  0x00007fbe1e875e59 in TUnixSystem::StackTrace() () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#3  0x00007fbe1e877a5c in TUnixSystem::DispatchSignals(ESignals) () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#4  <signal handler called>
#5  0x00000000004103f7 in get_fitParBias ()
#6  0x0000000000411bc7 in storeBias_CCprior ()
#7  0x00000000004178d8 in set_CUTMASK ()
#8  0x0000000000417911 in compute_CUTMASK ()
#9  0x000000000042d8a5 in read_simFile_CCprior ()
#10 0x000000000042db22 in prepare_CCprior ()
#11 0x0000000000430372 in SALT2mu_DRIVER_INIT ()
#12 0x0000000000431204 in main ()
===========================================================

```

I created the folder:
`$SNANA_DEBUG/mvincenzi/BBC_segfault`
on midway. The file FAILING.CMD allows to reproduce the error.

I also created the file WORKING.CMD to provide a **working** example that uses the exact same biascor sim and CCprior file, but different input FITRES file. 

Maria

**Comment by maria-vincenzi** [comment]
I found the bug and it was that one fo the samples had 0 or 1 element only after cuts

**Comment by RickKessler** [comment]
data include only LOWZ, but CC_prior is only high-z. Fixed SALT2mu to give more sensible error message.
