### ISSUE TITLE
AssertionError: Oh no, looks like you have a different number of bins/supernova for your systematic and this is not good.

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#967]
Output directory: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_D5YR_SIM`

I am getting the below error and am not sure how to approach debugging it.
```
  14 [   ERROR |           manager.py:473]       Done file reported failure. Check output log /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_D5YR_SIM/7_CREATE_COV/ALL_G10NOM_SIGINT_COLOR/output.log
  13 [   ERROR |           manager.py:473]       Found error in file /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_D5YR_SIM/7_CREATE_COV/ALL_G10NOM_SIGINT_COLOR/output.log, excerpt below
  12 [   ERROR |           manager.py:473]       Excerpt:    [   ERROR | create_covariance.py:1391]   Oh no, looks like you have a different number of bins/supernova for your systematic and this is not good.
  11 [   ERROR |           manager.py:473]       Excerpt:    Traceback (most recent call last):
  10 [   ERROR |           manager.py:473]       Excerpt:      File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1389, in <module>
   9 [   ERROR |           manager.py:473]       Excerpt:        create_covariance(config, args)
   8 [   ERROR |           manager.py:473]       Excerpt:      File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 1305, in create_covariance
   7 [   ERROR |           manager.py:473]       Excerpt:        extracovdict)
   6 [   ERROR |           manager.py:473]       Excerpt:      File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 690, in get_contributions
   5 [   ERROR |           manager.py:473]       Excerpt:        cov, summary = get_cov_from_diff(df, df_compare, fitopt_scale)
   4 [   ERROR |           manager.py:473]       Excerpt:      File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/create_covariance.py", line 612, in get_cov_from_diff
   3 [   ERROR |           manager.py:473]       Excerpt:        "Oh no, looks like you have a different number of bins/supernova " \
   2 [   ERROR |           manager.py:473]       Excerpt:    AssertionError: Oh no, looks like you have a different number of bins/supernova for your systematic and this is not good.
   1 [   ERROR |           manager.py:473]       FAILED: CreateCov ALL_G10NOM_SIGINT_COLOR task (wall time 0:01:14, 1 jobs, deps ['G10NOM_SIGINT_COLOR'])
```

**Comment by OmegaLambda1998** [comment]
Following your slack advice to add `FLAG_USE_SAME_EVENTS: 1` I now have the following errors:
Directory: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_D5YR_SIM/2_LCFIT/Dsys_SIMDES5YRCC/output`

Error in `SPLIT_JOBS_LCFIT/CPU0049*.LOG`:

```
  1 Error tokenizing data. C error: Expected 81 fields in line 1842, saw 83
  2 Traceback (most recent call last):
  3   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 420, in run_merge_driver
  4     program.merge_driver()
  5   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 1443, in merge_driver
  6     misc_info     = self.get_misc_merge_info()
  7   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_lcfit.py", line 1919, in get_misc_merge_info
  8     nevt_common = self.get_nevt_common(version)
  9   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_lcfit.py", line 1945, in get_nevt_common
 10     df = pd.read_csv(FITRES_FILE, delim_whitespace=True, comment="#")
 11   File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
 12     return func(*args, **kwargs)
 13   File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
 14     return _read(filepath_or_buffer, kwds)
 15   File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
 16     return parser.read(nrows)
 17   File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
 18     index, columns, col_dict = self._engine.read(nrows)
 19   File "/project2/rkessler/PRODUCTS/miniconda/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
 20     chunks = self._reader.read_low_memory(nrows)
 21   File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
 22   File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
 23   File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
 24   File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
 25 pandas.errors.ParserError: Error tokenizing data. C error: Expected 81 fields in line 1842, saw 83
 ```

**Comment by RickKessler** [comment]
ok, here is the problem. Take a look at $SCRATCH_SIMDIR/PIP_PA_D5YR_SIM_SIMDES5YRCC/PIP_PA_D5YR_SIM_SIMDES5YRCC.README 
The first model (NONIaMODEL0) only has 127 events total, and the LC fit job is split into 50 cores. 127/50 ~ 2.5, but with Poisson fluctuations some of the cores have zero events. When there are zero events in the first model, the 2nd model defines the output table columns, which are different.

For SNIa+SNCC mix, there is code to protect column definitions to always be SNIa columns. However, there is no such protection for combining SNCC models.

A short-term fix is to change the model order so that a higher-stat model is first (e.g., NONIaMODEL2 with ~3000 events), and this will always give a consistent set of table columns. I will need to think about a more robust solution.

Please leave this output so that I can reproduce the different table columns with FITOPT013_SPLIT042 and FITOPT013_SPLIT043

**Comment by RickKessler** [comment]
Table column mis-alignment might be fixed; try again.
