### ISSUE TITLE
Error when combining -chi2grid and -minchi2

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#987]
Output: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_FR_LAMBDACDM/8_COSMOFIT/WFIT/WFIT_SN_OMW_NO_OMPRI/output/SCRIPTS_WFIT/CPU0024_JOBLIST_midway2-login1.LOG`

Error:

```
 50 Traceback (most recent call last):
 49   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 420, in run_merge_driver
 48     program.merge_driver()
 47   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 1451, in merge_driver
 46     if cleanup_flag:  self.merge_cleanup_final()
 45   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_wfit.py", line 812, in merge_cleanup_final
 44     self.make_wfit_summary()
 43   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_wfit.py", line 856, in make_wfit_summary
 42     wfit_values_dict = util.get_wfit_values(wfit_yaml)
 41   File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 88, in get_wfit_values
 40     w_sig_hi = wfit_yaml['wsig_hi']
 39 KeyError: 'wsig_hi'
```

Looking at the associated .YAML files, it seems like there's a `wsig_up` column rather than a `wsig_hi` column

**Comment by RickKessler** [comment]
fixed silly bug; wFit wrote wsig_up, but submit_batch was trying to read wsig_hi.
